version: '3.2'
services:

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:6.7.0
    container_name: elasticsearch
    environment:
      - cluster.name=docker-cluster
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - /data/elasticsearch:/usr/share/elasticsearch/data
    ports:
      - 9200:9200
    networks:
      - esnet

  elasticsearch2:
    image: docker.elastic.co/elasticsearch/elasticsearch:6.7.0
    container_name: elasticsearch2
    environment:
      - cluster.name=docker-cluster
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
      - "discovery.zen.ping.unicast.hosts=elasticsearch"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - /data/elasticsearch2:/usr/share/elasticsearch/data
    networks:
      - esnet
    restart: always

  kibana:
    image: docker.elastic.co/kibana/kibana:6.7.0
    container_name: kibana
    ports:
      - "5601:5601"
    restart: always
    networks:
      - esnet

  logstash:
    image: docker.elastic.co/logstash/logstash:6.7.0
    container_name: logstash
    volumes:
      - /tmp/Log/:/usr/share/logstash/Log
      - /logstash/:/usr/share/logstash/pipeline/
    restart: always
    networks:
    - esnet

  redis:
    image: redis
    container_name: redis
    command: redis-server --requirepass ada7ec30bc148d6
    ports:
      - "6379:6379"
    volumes:
      - /data/redis/:/data
    restart: always
    networks:
      - esnet

  filebeat:
    container_name: filebeat
    image: docker.elastic.co/beats/filebeat:6.7.0
    volumes:
      - /tmp/Log/:/usr/share/filebeat/Log
      - /filebeat/:/usr/share/filebeat/filebeat.yml
    restart: always
    networks:
      - esnet

  dotnetcoreapi:
    container_name: netcorenlog
    image: dotnetcoreapi:v2
    ports: 
      - 8181:80
    volumes: 
      - /tmp/Log:/app/Log

networks:
  esnet: