version: '3'
services:
  elasticsearch:
    build: elasticsearch/
    container_name: elasticsearch
    ports:
    - "9200:9200"
    - "9300:9300"
    volumes:
    - /data/elasticsearch:/usr/share/elasticsearch/data
    restart: always
  kibana:
    image: docker.elastic.co/kibana/kibana:6.5.4
    container_name: kibana
    ports:
    - "5601:5601"
    restart: always
    links:
    - elasticsearch:elasticsearch
  logstash:
    build: logstash/
    container_name: logstash
    volumes:
    - /tmp/Log/:/usr/share/logstash/Log
    - /tmp/logstash/pipeline:/usr/share/logstash/pipeline/
    restart: always
    links:
    - elasticsearch:elasticsearch